"use client";

import {
  AlertTriangle,
  Bot,
  CheckCircle2,
  FileWarning,
  Lock,
  Scale,
  Server,
  ShieldAlert,
  Stethoscope,
} from "lucide-react";
import { useRouter } from "next/navigation";

export default function AgentTermsPage() {

    const router = useRouter();

  const sections = [
    {
      icon: ShieldAlert,
      title: "Acceptance of Terms",
      content:
        "By using this AI agent, you agree to follow these terms and conditions. This platform is provided as an informational and productivity tool mainly focused on DevOps, software engineering, infrastructure automation, cloud workflows, deployment support, debugging assistance, and related technical operations.",
    },
    {
      icon: Bot,
      title: "AI Generated Responses",
      content:
        "This AI model may generate inaccurate, incomplete, outdated, misleading, or entirely incorrect information. Responses are generated probabilistically and should never be considered guaranteed truth, professional advice, or verified facts. You must independently validate all critical outputs before acting on them.",
    },
    {
      icon: Server,
      title: "Primary Purpose of This Agent",
      content:
        "This agent is primarily designed for DevOps and engineering-related assistance including CI/CD pipelines, Docker, Kubernetes, cloud deployments, infrastructure-as-code, monitoring, Linux systems, automation scripts, observability, backend workflows, developer tooling, and debugging support.",
    },
    {
      icon: AlertTriangle,
      title: "Use at Your Own Risk",
      content:
        "Any action you take based on the outputs of this AI system is strictly at your own risk. The creators, maintainers, or providers of this platform are not responsible for infrastructure failures, production outages, security incidents, data loss, downtime, broken deployments, financial loss, or any other damages resulting from the use of generated content.",
    },
    {
      icon: Stethoscope,
      title: "Medical & Health Disclaimer",
      content:
        "This AI agent is NOT a medical system and must never be relied upon for health-related decisions, diagnosis, treatment, prescriptions, mental health evaluation, or emergency guidance. Health-related responses may be completely wrong or dangerous. Always consult a qualified doctor, physician, or licensed healthcare professional for any medical concerns. If this is an emergency, contact local emergency services immediately.",
    },
    {
      icon: Lock,
      title: "Security & Credentials",
      content:
        "Never share passwords, API keys, SSH credentials, private certificates, production secrets, banking information, or sensitive personal data with this AI agent. While reasonable precautions may exist, no AI system should be treated as a secure vault for confidential information.",
    },
    {
      icon: Scale,
      title: "Compliance & Responsibility",
      content:
        "You are solely responsible for ensuring that your usage complies with applicable laws, regulations, organizational policies, licensing terms, and security requirements. Generated scripts or commands should always be reviewed before execution in development, staging, or production environments.",
    },
    {
      icon: FileWarning,
      title: "No Guarantees",
      content:
        "This service is provided on an 'as-is' and 'as-available' basis without warranties of any kind. We do not guarantee uptime, correctness, reliability, availability, compatibility, or fitness for a particular purpose. Sometimes the AI might confidently spit absolute nonsense. Yeah, AI can be dumb as hell sometimes, so double-check important stuff before pushing to prod bro.",
    },
  ];

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 px-6 py-16">
      <div className="mx-auto max-w-5xl">
      <button onClick={()=>router.back()} >Back</button>
        {/* Header */}
        <div className="mb-14 text-center">
          <div className="mb-5 flex justify-center">
            <div className="rounded-2xl bg-zinc-900 p-4 border border-zinc-800">
              <ShieldAlert className="h-12 w-12 text-yellow-400" />
            </div>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
            AI Agent Terms & Conditions
          </h1>

          <p className="mt-5 text-zinc-400 text-lg max-w-3xl mx-auto leading-8">
            Please read these terms carefully before using this AI agent.
            This platform is mainly intended for DevOps and engineering
            assistance. Responses generated by AI may contain mistakes,
            hallucinations, or incomplete information.
          </p>
        </div>

        {/* Important Warning */}
        <div className="mb-12 rounded-2xl border border-yellow-500/30 bg-yellow-500/10 p-6">
          <div className="flex items-start gap-4">
            <AlertTriangle className="mt-1 h-7 w-7 text-yellow-400 shrink-0" />

            <div>
              <h2 className="text-xl font-semibold text-yellow-300">
                Important Notice
              </h2>

              <p className="mt-3 text-zinc-300 leading-7">
                AI-generated outputs are not guaranteed to be accurate. Always
                verify deployment scripts, infrastructure changes, commands,
                security configurations, and production actions before using
                them in real systems. Never blindly copy-paste random AI stuff
                into production unless you enjoy chaos and 3AM incident calls.
              </p>
            </div>
          </div>
        </div>

        {/* Sections */}
        <div className="grid gap-6">
          {sections.map((section, index) => {
            const Icon = section.icon;

            return (
              <div
                key={index}
                className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-6 transition hover:border-zinc-700 hover:bg-zinc-900"
              >
                <div className="flex items-start gap-4">
                  <div className="rounded-xl bg-zinc-800 p-3">
                    <Icon className="h-6 w-6 text-cyan-400" />
                  </div>

                  <div>
                    <h2 className="text-2xl font-semibold">
                      {section.title}
                    </h2>

                    <p className="mt-3 text-zinc-400 leading-8">
                      {section.content}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="mt-14 rounded-2xl border border-green-500/20 bg-green-500/10 p-6">
          <div className="flex items-start gap-4">
            <CheckCircle2 className="mt-1 h-7 w-7 text-green-400 shrink-0" />

            <div>
              <h2 className="text-xl font-semibold text-green-300">
                Final Reminder
              </h2>

              <p className="mt-3 text-zinc-300 leading-7">
                Always review AI-generated commands, infrastructure templates,
                scripts, and recommendations before execution. This system is a
                helper tool, not a replacement for engineering judgment,
                security reviews, operational testing, or professional medical
                advice.
              </p>
            </div>
          </div>
        </div>

        <p className="mt-10 text-center text-sm text-zinc-500">
          © 2026 AI DevOps Agent. All rights reserved.
        </p>
      </div>
    </div>
  );
}